use crate::error::{SanosError, SanosResult};
use crate::market::CompletionConfig;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OmegaConfig {
    Zero,
    One,
    Both,
}

impl Default for OmegaConfig {
    fn default() -> Self {
        OmegaConfig::One
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub struct KernelConfig {
    /// `omega = Zero` => `linear_call` constraints.
    /// `omega = One` => `call` constraints.
    /// `omega = Both` => enforce both blocks in the same LP.
    pub omega: OmegaConfig,
}

impl Default for KernelConfig {
    fn default() -> Self {
        Self { omega: OmegaConfig::default() }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub enum ObjectiveConfig {
    /// Hard constraints: model prices must lie within bid/ask.
    HardBidAsk,

    /// SANOS paper-style robust objective:
    /// - w * (epsilon_inside * |mid - model|
    ///      + slack_penalty * (max(0, bid-model) + max(0, model-ask)))
    ///
    ///   where default `w` follows Eq. (26): `quote.weight / (ask-bid)`.
    HingeBidAsk {
        slack_penalty: f64,
        epsilon_inside: f64,
    },

    /// L1 fit to mid prices (typically with optional extra constraints).
    L1Mid { weight: f64 },
}

impl Default for ObjectiveConfig {
    fn default() -> Self {
        ObjectiveConfig::HingeBidAsk {
            slack_penalty: 1.0,
            epsilon_inside: 1e-8,
        }
    }
}

impl ObjectiveConfig {
    pub fn validate(&self) -> SanosResult<()> {
        match self {
            ObjectiveConfig::HardBidAsk => Ok(()),
            ObjectiveConfig::HingeBidAsk { slack_penalty, epsilon_inside } => {
                if !slack_penalty.is_finite() {
                    return Err(SanosError::NonFinite { field: "objective.slack_penalty", value: *slack_penalty });
                }
                if *slack_penalty <= 0.0 {
                    return Err(SanosError::InvalidBound {
                        field: "objective.slack_penalty",
                        value: *slack_penalty,
                        min: f64::MIN_POSITIVE,
                        max: f64::INFINITY,
                    });
                }
                if !epsilon_inside.is_finite() {
                    return Err(SanosError::NonFinite { field: "objective.epsilon_inside", value: *epsilon_inside });
                }
                if *epsilon_inside < 0.0 {
                    return Err(SanosError::InvalidBound {
                        field: "objective.epsilon_inside",
                        value: *epsilon_inside,
                        min: 0.0,
                        max: f64::INFINITY,
                    });
                }
                Ok(())
            }
            ObjectiveConfig::L1Mid { weight } => {
                if !weight.is_finite() {
                    return Err(SanosError::NonFinite { field: "objective.weight", value: *weight });
                }
                if *weight <= 0.0 {
                    return Err(SanosError::InvalidBound {
                        field: "objective.weight",
                        value: *weight,
                        min: f64::MIN_POSITIVE,
                        max: f64::INFINITY,
                    });
                }
                Ok(())
            }
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub struct LpConfig {
    pub enforce_simplex: bool,          // sum_i q_{j,i} = 1
    pub enforce_nonnegativity: bool,    // q_{j,i} >= 0
    pub include_time_constraints: bool, // U/R blocks
}

impl Default for LpConfig {
    fn default() -> Self {
        Self {
            enforce_simplex: true,
            enforce_nonnegativity: true,
            include_time_constraints: true,
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InitPriceProxyConfig {
    Mid,
    Bid,
    Ask,
}

impl Default for InitPriceProxyConfig {
    fn default() -> Self {
        InitPriceProxyConfig::Mid
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WarmStartMode {
    /// No warm-start: leave initialization entirely to the LP solver backend.
    None,
    /// Build warm-start from synthetic calls generated by the backbone
    /// at market strikes.
    BackboneSynthetic,
}

impl Default for WarmStartMode {
    fn default() -> Self {
        WarmStartMode::None
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub struct InitializationConfig {
    /// Warm-start source policy.
    #[cfg_attr(feature = "serde", serde(default))]
    pub mode: WarmStartMode,
    /// Market quote proxy used to build the raw call curve.
    pub price_proxy: InitPriceProxyConfig,
    /// Numerical tolerance used for strict warm-start feasibility checks.
    pub feasibility_tol: f64,
    /// Practical market completion (Remark 2.8) config used for synthetic warm-start.
    #[cfg_attr(feature = "serde", serde(default))]
    pub market_completion: CompletionConfig,
}

impl Default for InitializationConfig {
    fn default() -> Self {
        Self {
            mode: WarmStartMode::default(),
            price_proxy: InitPriceProxyConfig::Mid,
            feasibility_tol: 1e-8,
            market_completion: CompletionConfig::default(),
        }
    }
}

impl InitializationConfig {
    pub fn uses_warm_start(&self) -> bool {
        self.mode != WarmStartMode::None
    }

    pub fn validate(&self) -> SanosResult<()> {
        if !self.feasibility_tol.is_finite() {
            return Err(SanosError::NonFinite {
                field: "initialization.feasibility_tol",
                value: self.feasibility_tol,
            });
        }
        if self.feasibility_tol < 0.0 {
            return Err(SanosError::InvalidBound {
                field: "initialization.feasibility_tol",
                value: self.feasibility_tol,
                min: 0.0,
                max: f64::INFINITY,
            });
        }
        if self.mode == WarmStartMode::BackboneSynthetic {
            self.market_completion.validate()?;
        }
        Ok(())
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub enum LpSolverConfig {
    /// Pure Rust LP solver backend (no external binary required).
    Microlp,

    /// External CBC solver binary (requires `cbc` installed in PATH).
    Cbc { msg: bool, time_limit_sec: Option<u64> },
}

impl Default for LpSolverConfig {
    fn default() -> Self {
        LpSolverConfig::Microlp
    }
}

impl LpSolverConfig {
    pub fn validate_available(&self) -> SanosResult<()> {
        match self {
            LpSolverConfig::Microlp => {
                if cfg!(feature = "lp-microlp") {
                    Ok(())
                } else {
                    Err(SanosError::NotImplemented {
                        what: "Microlp solver selected but feature `lp-microlp` is not enabled.",
                    })
                }
            }
            LpSolverConfig::Cbc { .. } => {
                if cfg!(feature = "lp-cbc") {
                    Ok(())
                } else {
                    Err(SanosError::NotImplemented {
                        what: "CBC solver selected but feature `lp-cbc` is not enabled.",
                    })
                }
            }
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub struct FitConfig {
    pub kernel: KernelConfig,
    pub objective: ObjectiveConfig,
    pub lp: LpConfig,
    pub solver: LpSolverConfig,
    #[cfg_attr(feature = "serde", serde(default))]
    pub initialization: InitializationConfig,
}

impl Default for FitConfig {
    fn default() -> Self {
        Self {
            kernel: KernelConfig::default(),
            objective: ObjectiveConfig::default(),
            lp: LpConfig::default(),
            solver: LpSolverConfig::default(),
            initialization: InitializationConfig::default(),
        }
    }
}

impl FitConfig {
    pub fn uses_warm_start(&self) -> bool {
        self.initialization.uses_warm_start()
    }

    pub fn validate(&self) -> SanosResult<()> {
        self.solver.validate_available()?;
        self.objective.validate()?;
        self.initialization.validate()?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fit_config_validate_checks_solver_backend_availability() {
        let cfg = FitConfig::default();

        #[cfg(feature = "lp-microlp")]
        assert!(cfg.validate().is_ok());

        #[cfg(not(feature = "lp-microlp"))]
        assert!(matches!(cfg.validate(), Err(SanosError::NotImplemented { .. })));
    }

    #[test]
    fn cbc_solver_validation_is_feature_gated() {
        let cfg = LpSolverConfig::Cbc {
            msg: false,
            time_limit_sec: None,
        };

        #[cfg(feature = "lp-cbc")]
        assert!(cfg.validate_available().is_ok());

        #[cfg(not(feature = "lp-cbc"))]
        assert!(matches!(
            cfg.validate_available(),
            Err(SanosError::NotImplemented { .. })
        ));
    }
}
