#!/usr/bin/env python3
"""
Generate calibration quality plots from SANOS JSON outputs.

Expected inputs:
- diagnostics.json generated by `sanos-cli calibrate --out ...`
- optionally surface.json for dense surface and density-comparison plots
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

try:
    import matplotlib.pyplot as plt
    import numpy as np
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "Missing plotting dependencies. Install matplotlib and numpy. "
        f"Import error: {exc}"
    )


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def group_quotes_by_maturity(quotes: list[dict]) -> dict[float, list[dict]]:
    groups: dict[float, list[dict]] = {}
    for q in quotes:
        t = float(q["maturity"])
        groups.setdefault(t, []).append(q)
    for chain in groups.values():
        chain.sort(key=lambda q: float(q["strike"]))
    return groups


def pick_maturities(maturities: list[float], max_panels: int) -> list[float]:
    if len(maturities) <= max_panels:
        return maturities
    idx = np.linspace(0, len(maturities) - 1, max_panels)
    picked = sorted({int(round(i)) for i in idx})
    return [maturities[i] for i in picked]


def setup_panel_grid(n: int) -> tuple[plt.Figure, np.ndarray]:
    ncols = min(3, max(1, n))
    nrows = int(math.ceil(n / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(5.5 * ncols, 3.9 * nrows))
    axes_arr = np.atleast_1d(axes).ravel()
    return fig, axes_arr


def finalize_panel_grid(
    fig: plt.Figure, axes_arr: np.ndarray, n_used: int, out_path: Path, title: str
) -> None:
    for j in range(n_used, len(axes_arr)):
        axes_arr[j].set_visible(False)
    fig.suptitle(title, fontsize=13, y=0.99)
    fig.tight_layout(rect=(0, 0, 1, 0.965))
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_smile_fits(diagnostics: dict, out_path: Path, max_panels: int) -> None:
    quotes = diagnostics.get("quotes", [])
    if not quotes:
        return

    groups = group_quotes_by_maturity(quotes)
    maturities = sorted(groups.keys())
    selected = pick_maturities(maturities, max_panels=max_panels)

    fig, axes_arr = setup_panel_grid(len(selected))
    for i, t in enumerate(selected):
        ax = axes_arr[i]
        chain = groups[t]
        k = np.array([float(q["strike"]) for q in chain], dtype=float)
        bid = np.array([float(q["bid"]) for q in chain], dtype=float)
        ask = np.array([float(q["ask"]) for q in chain], dtype=float)
        mid = np.array([float(q["mid"]) for q in chain], dtype=float)
        model = np.array([float(q["model"]) for q in chain], dtype=float)

        ax.fill_between(k, bid, ask, color="#d4e6f8", alpha=0.92, label="Bid/Ask")
        ax.plot(k, mid, color="#2f6690", linewidth=2.0, label="Mid")
        ax.plot(k, model, color="#d1495b", linewidth=2.0, label="Model")
        inside = np.mean(np.array([bool(q["inside_bid_ask"]) for q in chain], dtype=bool))
        ax.set_title(f"T={t:.3f}  inside={inside:.1%}", fontsize=10)
        ax.set_xlabel("Strike")
        ax.set_ylabel("Call price")
        ax.grid(alpha=0.25)
        ax.legend(loc="best", fontsize=8, frameon=True, framealpha=0.9)

    finalize_panel_grid(
        fig,
        axes_arr,
        len(selected),
        out_path,
        "Calibration fit on call-price smiles",
    )


def plot_iv_smile_fits(diagnostics: dict, out_path: Path, max_panels: int) -> None:
    quotes = diagnostics.get("quotes", [])
    if not quotes:
        return

    groups = group_quotes_by_maturity(quotes)
    maturities = sorted(groups.keys())
    selected = pick_maturities(maturities, max_panels=max_panels)
    fig, axes_arr = setup_panel_grid(len(selected))

    for i, t in enumerate(selected):
        ax = axes_arr[i]
        chain = groups[t]
        k = np.array([float(q["strike"]) for q in chain], dtype=float)

        bid_iv = np.array(
            [
                np.nan if q.get("bid_iv") is None else float(q["bid_iv"])
                for q in chain
            ],
            dtype=float,
        )
        ask_iv = np.array(
            [
                np.nan if q.get("ask_iv") is None else float(q["ask_iv"])
                for q in chain
            ],
            dtype=float,
        )
        mid_iv = np.array(
            [
                np.nan if q.get("mid_iv") is None else float(q["mid_iv"])
                for q in chain
            ],
            dtype=float,
        )
        model_iv = np.array(
            [
                np.nan if q.get("model_iv") is None else float(q["model_iv"])
                for q in chain
            ],
            dtype=float,
        )
        valid = np.isfinite(mid_iv) & np.isfinite(model_iv)
        iv_mae = (
            float(np.mean(np.abs(model_iv[valid] - mid_iv[valid])))
            if np.any(valid)
            else float("nan")
        )

        ax.fill_between(k, bid_iv, ask_iv, color="#e2f0d9", alpha=0.9, label="Bid/Ask IV")
        ax.plot(k, mid_iv, color="#3d5a80", linewidth=2.0, label="Mid IV")
        ax.plot(k, model_iv, color="#e76f51", linewidth=2.0, label="Model IV")
        ax.set_title(
            f"T={t:.3f}  MAE(iv)={iv_mae:.3e}" if np.isfinite(iv_mae) else f"T={t:.3f}",
            fontsize=10,
        )
        ax.set_xlabel("Strike")
        ax.set_ylabel("Implied vol")
        ax.grid(alpha=0.25)
        ax.legend(loc="best", fontsize=8, frameon=True, framealpha=0.9)

    finalize_panel_grid(
        fig,
        axes_arr,
        len(selected),
        out_path,
        "Calibration fit on implied-volatility smiles",
    )


def plot_residual_heatmap(diagnostics: dict, out_path: Path) -> None:
    quotes = diagnostics.get("quotes", [])
    if not quotes:
        return

    x = np.array([math.log(float(q["strike"])) for q in quotes], dtype=float)
    y = np.array([float(q["maturity"]) for q in quotes], dtype=float)
    z = np.array([float(q["residual_spread_norm"]) for q in quotes], dtype=float)

    finite = np.isfinite(x) & np.isfinite(y) & np.isfinite(z)
    x = x[finite]
    y = y[finite]
    z = z[finite]
    if z.size == 0:
        return

    vmax = max(1.0, float(np.nanpercentile(np.abs(z), 95)))
    fig, ax = plt.subplots(figsize=(10, 5.4))
    contour = ax.tricontourf(
        x,
        y,
        z,
        levels=26,
        cmap="RdBu_r",
        vmin=-vmax,
        vmax=vmax,
    )
    ax.scatter(x, y, s=8, color="black", alpha=0.25)
    cbar = fig.colorbar(contour, ax=ax, pad=0.02)
    cbar.set_label("Residual / half-spread")

    ax.set_xlabel("log(Strike)")
    ax.set_ylabel("Maturity")
    ax.set_title("Residual heatmap (normalized by bid/ask spread)")
    ax.grid(alpha=0.2)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_quality_summary(diagnostics: dict, out_path: Path) -> None:
    per = diagnostics.get("per_maturity", [])
    quotes = diagnostics.get("quotes", [])
    summary = diagnostics.get("summary", {})

    t = np.array([float(x["maturity"]) for x in per], dtype=float)
    inside = np.array([float(x["inside_bid_ask_ratio"]) for x in per], dtype=float)
    mae_mid = np.array([float(x["mae_mid"]) for x in per], dtype=float)
    rmse_mid = np.array([float(x["rmse_mid"]) for x in per], dtype=float)
    mae_spread = np.array([float(x["mae_spread_norm"]) for x in per], dtype=float)
    mae_iv = np.array(
        [
            np.nan if x.get("mae_iv") is None else float(x["mae_iv"])
            for x in per
        ],
        dtype=float,
    )
    res = np.array([float(q["residual_spread_norm"]) for q in quotes], dtype=float)
    res = res[np.isfinite(res)]

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    ax0, ax1, ax2, ax3 = axes.ravel()

    if t.size > 0:
        ax0.plot(t, inside, marker="o", color="#2f6690")
    ax0.axhline(float(summary.get("inside_bid_ask_ratio", 0.0)), color="#8d99ae", linestyle="--")
    ax0.set_ylim(0.0, 1.02)
    ax0.set_title("Inside bid/ask ratio by maturity")
    ax0.set_xlabel("Maturity")
    ax0.grid(alpha=0.25)

    if t.size > 0:
        ax1.plot(t, mae_mid, marker="o", label="MAE(mid)", color="#d1495b")
        ax1.plot(t, rmse_mid, marker="o", label="RMSE(mid)", color="#2a9d8f")
        if np.any(np.isfinite(mae_iv)):
            ax1.plot(t, mae_iv, marker="o", label="MAE(iv)", color="#6d597a")
    ax1.set_title("Absolute error metrics")
    ax1.set_xlabel("Maturity")
    ax1.legend(frameon=False)
    ax1.grid(alpha=0.25)

    if t.size > 0:
        ax2.plot(t, mae_spread, marker="o", color="#5b8e7d")
    ax2.axhline(1.0, color="#8d99ae", linestyle="--")
    ax2.set_title("MAE of normalized residual")
    ax2.set_xlabel("Maturity")
    ax2.grid(alpha=0.25)

    if res.size > 0:
        lim = max(3.0, float(np.nanpercentile(np.abs(res), 98)))
        bins = np.linspace(-lim, lim, 41)
        ax3.hist(res, bins=bins, color="#4c956c", alpha=0.9, edgecolor="white")
        ax3.axvline(-1.0, color="#d1495b", linestyle="--")
        ax3.axvline(1.0, color="#d1495b", linestyle="--")
    ax3.set_title("Distribution of residual / half-spread")
    ax3.set_xlabel("Normalized residual")
    ax3.grid(alpha=0.2)

    mae_iv_summary = summary.get("mae_iv")
    rmse_iv_summary = summary.get("rmse_iv")
    iv_text = ""
    if mae_iv_summary is not None and rmse_iv_summary is not None:
        iv_text = f",  MAE(iv)={float(mae_iv_summary):.3e},  RMSE(iv)={float(rmse_iv_summary):.3e}"
    fig.suptitle(
        "Calibration diagnostics  "
        f"inside={float(summary.get('inside_bid_ask_ratio', 0.0)):.1%},  "
        f"MAE(mid)={float(summary.get('mae_mid', 0.0)):.3e},  "
        f"RMSE(mid)={float(summary.get('rmse_mid', 0.0)):.3e},  "
        f"MAE(norm)={float(summary.get('mae_spread_norm', 0.0)):.3f}"
        f"{iv_text}",
        fontsize=12,
        y=0.99,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def plot_surface_heatmap(surface: dict, out_path: Path) -> None:
    maturities = np.array(surface.get("maturities", []), dtype=float)
    strikes = np.array(surface.get("strikes", []), dtype=float)
    calls = np.array(surface.get("calls", []), dtype=float)
    if maturities.size == 0 or strikes.size == 0 or calls.size == 0:
        return
    if calls.shape != (maturities.size, strikes.size):
        return

    fig, ax = plt.subplots(figsize=(10, 5.4))
    mesh = ax.pcolormesh(
        np.log(strikes),
        maturities,
        calls,
        shading="auto",
        cmap="viridis",
    )
    cbar = fig.colorbar(mesh, ax=ax, pad=0.02)
    cbar.set_label("Call price")
    ax.set_xlabel("log(Strike)")
    ax.set_ylabel("Maturity")
    ax.set_title("Dense SANOS call surface")
    ax.grid(alpha=0.18)
    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def _interp_slice_at_maturity(
    maturities: np.ndarray, calls: np.ndarray, target_t: float
) -> np.ndarray:
    if target_t <= maturities[0]:
        return calls[0, :]
    if target_t >= maturities[-1]:
        return calls[-1, :]
    idx = int(np.searchsorted(maturities, target_t))
    t0 = maturities[idx - 1]
    t1 = maturities[idx]
    w = (target_t - t0) / max(t1 - t0, 1e-16)
    return (1.0 - w) * calls[idx - 1, :] + w * calls[idx, :]


def _second_derivative_non_uniform(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    # Central finite differences on non-uniform grid via numpy gradient chaining.
    d1 = np.gradient(y, x)
    d2 = np.gradient(d1, x)
    return d2


def plot_density_comparison(surface: dict, out_path: Path, max_panels: int) -> None:
    maturities = np.array(surface.get("maturities", []), dtype=float)
    strikes = np.array(surface.get("strikes", []), dtype=float)
    calls = np.array(surface.get("calls", []), dtype=float)
    marginals = surface.get("marginals", [])
    if (
        maturities.size == 0
        or strikes.size == 0
        or calls.size == 0
        or calls.shape != (maturities.size, strikes.size)
        or len(marginals) == 0
    ):
        return

    marginal_ts = sorted(float(m["maturity"]) for m in marginals)
    selected = pick_maturities(marginal_ts, max_panels=max_panels)
    marginal_by_t = {float(m["maturity"]): m for m in marginals}

    fig, axes_arr = setup_panel_grid(len(selected))
    for i, t in enumerate(selected):
        ax = axes_arr[i]
        c_slice = _interp_slice_at_maturity(maturities, calls, t)
        density_impl = _second_derivative_non_uniform(strikes, c_slice)
        density_impl = np.maximum(density_impl, 0.0)

        ax.plot(
            strikes,
            density_impl,
            color="#1d3557",
            linewidth=2.0,
            label=r"$\partial_{KK}C(T,K)$",
        )

        m = marginal_by_t.get(float(t))
        if m is not None:
            atoms = m.get("atoms", [])
            k_q = np.array([float(a["strike"]) for a in atoms], dtype=float)
            w_q = np.array([float(a["weight"]) for a in atoms], dtype=float)
            ax.vlines(k_q, 0.0, w_q, color="#e76f51", alpha=0.85, linewidth=1.6, label="Discrete q atoms")

        ax.set_title(f"T={t:.3f}", fontsize=10)
        ax.set_xlabel("Strike")
        ax.set_ylabel("Density")
        ax.grid(alpha=0.25)
        ax.legend(loc="best", fontsize=8, frameon=True, framealpha=0.9)

    finalize_panel_grid(
        fig,
        axes_arr,
        len(selected),
        out_path,
        "Implied density from call convexity vs SANOS discrete density",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot SANOS calibration quality")
    parser.add_argument("--diagnostics", required=True, help="Path to diagnostics.json")
    parser.add_argument("--surface", help="Path to surface.json")
    parser.add_argument("--outdir", required=True, help="Output directory for PNG files")
    parser.add_argument("--prefix", default="calibration", help="Output file prefix")
    parser.add_argument("--max-panels", type=int, default=6, help="Max maturity panels for smile plots")
    args = parser.parse_args()

    diagnostics_path = Path(args.diagnostics)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    diagnostics = load_json(diagnostics_path)

    smiles_path = outdir / f"{args.prefix}_smiles_fit.png"
    smiles_iv_path = outdir / f"{args.prefix}_smiles_iv_fit.png"
    heatmap_path = outdir / f"{args.prefix}_residual_heatmap.png"
    summary_path = outdir / f"{args.prefix}_quality_summary.png"

    plot_smile_fits(diagnostics, smiles_path, max_panels=max(1, args.max_panels))
    plot_iv_smile_fits(diagnostics, smiles_iv_path, max_panels=max(1, args.max_panels))
    plot_residual_heatmap(diagnostics, heatmap_path)
    plot_quality_summary(diagnostics, summary_path)

    print("Generated:", smiles_path)
    print("Generated:", smiles_iv_path)
    print("Generated:", heatmap_path)
    print("Generated:", summary_path)

    if args.surface:
        surface_path = Path(args.surface)
        if surface_path.exists():
            surface = load_json(surface_path)
            surface_heatmap_path = outdir / f"{args.prefix}_surface_heatmap.png"
            density_cmp_path = outdir / f"{args.prefix}_density_comparison.png"
            plot_surface_heatmap(surface, surface_heatmap_path)
            plot_density_comparison(surface, density_cmp_path, max_panels=max(1, args.max_panels))
            print("Generated:", surface_heatmap_path)
            print("Generated:", density_cmp_path)


if __name__ == "__main__":
    main()
